version: 0.0
os: linux
files:
  - source: /spring-boot-docker.jar
    destination: /tmp
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: root