version: '3.7'

services:
  patient-server:
    container_name: "spring-boot-docker"
    build:
      context: "spring-boot-docker"
    resttart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: ${MONGO_HOST_2}
      MONGO_USERNAME: ${MONGO_USERNAME_2}
      MONGO_PASSWORD: ${MONGO_PASSWORD_2}
      MONGO_DATABASE: ${MONGO_DATABASE_2}
    env_file:
      - .env
    healthcheck:
      test: exit 0
    hostname: patient-server
